machina/apps/forum/urls.py
"""
    Forum URLs
    ==========

    This module defines URL patterns associated with the django-machina's ``forum`` application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum`` application. """

    app_namespace = 'forum'

    index_view = get_class('forum.views', 'IndexView')
    forum_view = get_class('forum.views', 'ForumView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path('', self.index_view.as_view(), name='index'),
            path(
                'forum/<str:slug>-<int:pk>/',
                self.forum_view.as_view(),
                name='forum',
            ),
        ]


urlpatterns_factory = ForumURLPatternsFactory()

machina/apps/forum_conversation/urls.py
"""
    Forum conversation URLs
    =======================

    This module defines URL patterns associated with the django-machina's ``forum_conversation``
    application.

"""

from django.urls import include, path

from machina.apps.forum_conversation.forum_attachments.urls import \
    urlpatterns_factory as attachments_urlpatterns_factory
from machina.apps.forum_conversation.forum_polls.urls import \
    urlpatterns_factory as polls_urlpatterns_factory
from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class BaseForumConversationURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_conversation`` application. """

    app_namespace = 'forum_conversation'

    topic_view = get_class('forum_conversation.views', 'TopicView')
    topic_create_view = get_class('forum_conversation.views', 'TopicCreateView')
    topic_update_view = get_class('forum_conversation.views', 'TopicUpdateView')
    post_create_view = get_class('forum_conversation.views', 'PostCreateView')
    post_update_view = get_class('forum_conversation.views', 'PostUpdateView')
    post_delete_view = get_class('forum_conversation.views', 'PostDeleteView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        urlpatterns = super().get_urlpatterns()

        conversation_urlpatterns = [
            path(
                'topic/<str:slug>-<int:pk>/',
                self.topic_view.as_view(),
                name='topic',
            ),
            path('topic/create/', self.topic_create_view.as_view(), name='topic_create'),
            path(
                'topic/<str:slug>-<int:pk>/update/',
                self.topic_update_view.as_view(),
                name='topic_update',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/post/create/',
                self.post_create_view.as_view(),
                name='post_create',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/update/',
                self.post_update_view.as_view(),
                name='post_update',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/delete/',
                self.post_delete_view.as_view(),
                name='post_delete',
            ),
        ]

        urlpatterns += [
            path(
                'forum/<str:forum_slug>-<int:forum_pk>/',
                include(conversation_urlpatterns),
            ),
        ]

        return urlpatterns


class ForumAttachmentsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    attachments_urlpatterns_factory = attachments_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.attachments_urlpatterns_factory.urlpatterns)),
        ]


class ForumPollsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    polls_urlpatterns_factory = polls_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.polls_urlpatterns_factory.urlpatterns)),
        ]


class ForumConversationURLPatternsFactory(
    BaseForumConversationURLPatternsFactory, ForumAttachmentsURLPatternsFactory,
    ForumPollsURLPatternsFactory,
):
    """ Composite class combining conversation views with polls & attachments views. """


urlpatterns_factory = ForumConversationURLPatternsFactory()

machina/apps/forum_member/urls.py
"""
    Forum member URLs
    =================

    This module defines URL patterns associated with the django-machina's ``forum_member``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumMemberURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_member`` application. """

    app_namespace = 'forum_member'

    user_posts_list = get_class('forum_member.views', 'UserPostsView')
    forum_profile_detail_view = get_class('forum_member.views', 'ForumProfileDetailView')
    forum_profile_update_view = get_class('forum_member.views', 'ForumProfileUpdateView')
    topic_subscribe_view = get_class('forum_member.views', 'TopicSubscribeView')
    topic_unsubscribe_view = get_class('forum_member.views', 'TopicUnsubscribeView')
    topic_subscription_list_view = get_class('forum_member.views', 'TopicSubscriptionListView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'profile/edit/',
                self.forum_profile_update_view.as_view(),
                name='profile_update',
            ),
            path(
                'profile/<str:pk>/',
                self.forum_profile_detail_view.as_view(),
                name='profile',
            ),
            path(
                'profile/<str:pk>/posts/',
                self.user_posts_list.as_view(),
                name='user_posts',
            ),
            path(
                'subscriptions/',
                self.topic_subscription_list_view.as_view(),
                name='user_subscriptions',
            ),
            path(
                'topic/<int:pk>/subscribe/',
                self.topic_subscribe_view.as_view(),
                name='topic_subscribe',
            ),
            path(
                'topic/<int:pk>/unsubscribe/',
                self.topic_unsubscribe_view.as_view(),
                name='topic_unsubscribe',
            ),
        ]


urlpatterns_factory = ForumMemberURLPatternsFactory()

machina/core/urls.py
"""
    Machina core URL helpers
    ========================

    This module defines commons URLs helpers and abstractions used by django-machina to manage its
    URL patterns.

"""


class URLPatternsFactory:
    """ Allows to generate the URL patterns of a machina application.

    Machina's views and URLs use a tree of ``URLPatternsFactory`` instances in order to build the
    complete list of URL patterns of the forum application. This class provides a
    ``get_urlpatterns`` method that allows to define the URL patterns to include in the global list
    of URLs associated with the forum application. This behavior allows to easily override each of
    the views used to build the final list of URL patterns (because the views are imported
    dynamically). It also allows to append additional URLs to the generated URL patterns by
    subclassing the ``URLPatternsFactory`` subclass associated with the considered forum app.

    """

    app_namespace = None

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application.

        This method should be implemented in any subclass.
        """
        return []

    @property
    def urlpatterns(self):
        """ Returns a tuple containing the list of URL patterns and an app namespace. """
        return self.get_urlpatterns(), self.app_namespace

machina/urls.py
"""
    Machina URLs
    ============

    This module imports all the URLs defined by the forum-related applications.

"""

from django.conf.urls import include, url

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class BoardURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the whole forum application. """

    forum_urlpatterns_factory = get_class('forum.urls', 'urlpatterns_factory')
    conversation_urlpatterns_factory = get_class('forum_conversation.urls', 'urlpatterns_factory')
    feeds_urlpatterns_factory = get_class('forum_feeds.urls', 'urlpatterns_factory')
    member_urlpatterns_factory = get_class('forum_member.urls', 'urlpatterns_factory')
    moderation_urlpatterns_factory = get_class('forum_moderation.urls', 'urlpatterns_factory')
    search_urlpatterns_factory = get_class('forum_search.urls', 'urlpatterns_factory')
    tracking_urlpatterns_factory = get_class('forum_tracking.urls', 'urlpatterns_factory')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            url(r'', include(self.forum_urlpatterns_factory.urlpatterns)),
            url(r'', include(self.conversation_urlpatterns_factory.urlpatterns)),
            url(r'^feeds/', include(self.feeds_urlpatterns_factory.urlpatterns)),
            url(r'^member/', include(self.member_urlpatterns_factory.urlpatterns)),
            url(r'^moderation/', include(self.moderation_urlpatterns_factory.urlpatterns)),
            url(r'^search/', include(self.search_urlpatterns_factory.urlpatterns)),
            url(r'^tracking/', include(self.tracking_urlpatterns_factory.urlpatterns)),
        ]


urlpatterns_factory = BoardURLPatternsFactory()
urlpatterns = urlpatterns_factory.get_urlpatterns()

qcqi_web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include, re_path
from mainpage import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from . import settings
from machina import urls as machina_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('index',views.index),
    path('test',views.test),
    path('test/<int:num>', views.test, name='test'),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
    path('seminar',views.seminar_list_web),
    path('seminar/<int:id>', views.seminar_web, name='seminar_web'),
    path('Mini-Courses',views.class_list_web),
    path('class',views.class_list_web),
    path('Mini-Courses/<int:id>', views.class_web, name='class_web'),
    path('news',views.news_list_web),
    path('news/<int:id>', views.news_web, name='news_web'),
    path('people',views.people_list_web),
    path('people/<slug:name>', views.people_web, name='people_web'),
    path('themes',views.theme_list_web),
    path('themes/<int:id>', views.theme_web, name='theme_web'),
    path('conferences',views.conference_list_web),
    path('conferences/<int:id>', views.conference_web, name='conference_web'),
    path('papers',views.papers_web),
    path('papers/<str:categroy_name>',views.papers_list_web,name='categroy_name'),
    path('about',views.about_web),
    path('',views.index),
    path('forum/', include(machina_urls)),
    path('qcqi_account/', include('qcqi_account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

machina/apps/forum/models.py
"""
    Forum models
    ============

    This module defines models provided by the ``forum`` application.

"""

from machina.apps.forum.abstract_models import AbstractForum
from machina.core.db.models import model_factory


Forum = model_factory(AbstractForum)

machina/apps/forum_member/forms.py
"""
    Forum member forms
    ==================

    This module defines forms provided by the ``forum_member`` application.

"""

from django import forms

from machina.conf import settings as machina_settings
from machina.core.db.models import get_model


ForumProfile = get_model('forum_member', 'ForumProfile')


class ForumProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not machina_settings.PROFILE_AVATARS_ENABLED:
            del self.fields["avatar"]

    class Meta:
        model = ForumProfile
        fields = ['avatar', 'signature', ]

machina/apps/forum/views.py
"""
    Forum views
    ===========

    This module defines views provided by the ``forum`` application.

"""

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import ListView

from machina.apps.forum.signals import forum_viewed
from machina.conf import settings as machina_settings
from machina.core.db.models import get_model
from machina.core.loading import get_class


Forum = get_model('forum', 'Forum')
Topic = get_model('forum_conversation', 'Topic')

ForumVisibilityContentTree = get_class('forum.visibility', 'ForumVisibilityContentTree')
PermissionRequiredMixin = get_class('forum_permission.viewmixins', 'PermissionRequiredMixin')
TrackingHandler = get_class('forum_tracking.handler', 'TrackingHandler')


class IndexView(ListView):
    """ Displays the top-level forums. """

    context_object_name = 'forums'
    template_name = 'forum/index.html'

    def get_queryset(self):
        """ Returns the list of items for this view. """
        return ForumVisibilityContentTree.from_forums(
            self.request.forum_permission_handler.forum_list_filter(
                Forum.objects.all(), self.request.user,
            ),
        )

    def get_context_data(self, **kwargs):
        """ Returns the context data to provide to the template. """
        context = super(IndexView, self).get_context_data(**kwargs)
        visiblity_content_tree = context['forums']

        # Computes some global values.
        context['total_posts_count'] = sum(n.posts_count for n in visiblity_content_tree.top_nodes)
        context['total_topics_count'] = sum(
            n.topics_count for n in visiblity_content_tree.top_nodes
        )

        return context


class ForumView(PermissionRequiredMixin, ListView):
    """ Displays a forum and its topics. If applicable, its sub-forums can also be displayed. """

    context_object_name = 'topics'
    paginate_by = machina_settings.FORUM_TOPICS_NUMBER_PER_PAGE
    permission_required = ['can_read_forum', ]
    template_name = 'forum/forum_detail.html'
    view_signal = forum_viewed

    def get(self, request, **kwargs):
        """ Handles GET requests. """
        forum = self.get_forum()
        if forum.is_link:
            response = HttpResponseRedirect(forum.link)
        else:
            response = super(ForumView, self).get(request, **kwargs)
        self.send_signal(request, response, forum)
        return response

    def get_forum(self):
        """ Returns the forum to consider. """
        if not hasattr(self, 'forum'):
            self.forum = get_object_or_404(Forum, pk=self.kwargs['pk'])
        return self.forum

    def get_queryset(self):
        """ Returns the list of items for this view. """
        self.forum = self.get_forum()
        qs = (
            self.forum.topics
            .exclude(type=Topic.TOPIC_ANNOUNCE)
            .exclude(approved=False)
            .select_related('poster', 'last_post', 'last_post__poster')
        )
        return qs

    def get_controlled_object(self):
        """ Returns the controlled object. """
        return self.get_forum()

    def get_context_data(self, **kwargs):
        """ Returns the context data to provide to the template. """
        context = super(ForumView, self).get_context_data(**kwargs)

        # Insert the considered forum into the context
        context['forum'] = self.get_forum()

        # Get the list of forums that have the current forum as parent
        context['sub_forums'] = ForumVisibilityContentTree.from_forums(
            self.request.forum_permission_handler.forum_list_filter(
                context['forum'].get_descendants(), self.request.user,
            ),
        )

        # The announces will be displayed on each page of the forum
        context['announces'] = list(
            self.get_forum()
            .topics.select_related('poster', 'last_post', 'last_post__poster')
            .filter(type=Topic.TOPIC_ANNOUNCE)
        )

        # Determines the topics that have not been read by the current user
        context['unread_topics'] = TrackingHandler(self.request).get_unread_topics(
            list(context[self.context_object_name]) + context['announces'], self.request.user,
        )

        return context

    def send_signal(self, request, response, forum):
        """ Sends the signal associated with the view. """
        self.view_signal.send(
            sender=self, forum=forum, user=request.user, request=request, response=response,
        )

machina/templates/machina/forum_conversation/post_delete.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_conversation_tags %}

{% block sub_title %}{% trans "Delete post" %}{% endblock sub_title %}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card post-delete">
      <div class="card-header">
        <h3 class="m-0 card-title h5">{% trans "Delete post" %}</h3>
      </div>
      <div class="card-body">
        <div class="mb-3 warning-message">{% trans "Are you sure you want to delete this post?" %}</div>
        <form action="" method="post">{% csrf_token %}
          <input type="hidden" name="post" value="yes" />
          <button role="submit" class="btn btn-warning">{% trans "Yes, I'm sure" %}</button>
          <a href="{% url 'forum_conversation:topic' topic.forum.slug topic.forum.pk topic.slug topic.pk %}" class="btn btn-secondary">{% trans "No, take me back" %}</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

machina/templates/machina/forum_conversation/post_preview.html
{% load i18n %}
{% load forum_markup_tags %}

<div class="mb-3 row preview">
  <div class="col-12">
    <div class="card post post-preview">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12 post-content-wrapper">
            <h4 class="m-0 subject">{% trans "Preview:" %}&nbsp;{{ post_form.subject.value }}</h4>
            <hr />
            <div class="post-content">
              {{ post_form.content.value|safe|rendered }}
            </div>
            {% include "forum_conversation/forum_attachments/attachments_preview.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

machina/templates/machina/forum_conversation/topic_detail.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_conversation_tags %}
{% load forum_member_tags %}
{% load forum_permission_tags %}

{% block sub_title %}{{ topic.subject }}{% endblock sub_title %}

{% block content %}
<div class="row"><div class="col-12"><h1>{{ topic.subject }}</h1></div></div>
<div class="row">
  <div class="col-12 col-md-4 topic-actions-block">
  {% include "forum_conversation/partials/topic_detail_actions.html" %}
  </div>
  <div class="col-12 col-md-8 pagination-block">
  {% with "pagination-sm justify-content-end" as pagination_size %}
  {% include "partials/pagination.html" %}
  {% endwith %}
  </div>
</div>
<div class="row">
  <div class="col-12">
  {% for post in posts %}
    {% if forloop.first and post.is_topic_head and poll %}
    {% include "forum_conversation/forum_polls/poll_detail.html" %}
    {% endif %}
    <div id="{{ post.id }}" class="my-3 card post">
      <div class="card-body">
        <div class="row">
          <div class="col-md-10 post-content-wrapper">
            <div class="float-right post-controls">
              {% get_permission 'can_edit_post' post request.user as user_can_edit_post %}
              {% if user_can_edit_post %}
              <a href="{% if post.is_topic_head %}{% url 'forum_conversation:topic_update' forum.slug forum.pk topic.slug topic.pk %}{% else %}{% url 'forum_conversation:post_update' forum.slug forum.pk topic.slug topic.pk post.pk %}{% endif %}" class="btn btn-warning btn-sm" title="{% trans "Edit" %}"><i class="fas fa-edit"></i>&nbsp;{% trans "Edit" %}</a>
              {% endif %}
              {% get_permission 'can_delete_post' post request.user as user_can_delete_post %}
              {% if user_can_delete_post %}
              <a href="{% url 'forum_conversation:post_delete' forum.slug forum.pk topic.slug topic.pk post.pk %}" class="btn btn-danger btn-sm" title="{% trans "Delete" %}"><i class="fas fa-times"></i></a>
              {% endif %}
            </div>
              {% spaceless %}
              <h4 class="m-0 subject">
                {{ post.subject }}
                &nbsp;<a href="{% url 'forum_conversation:topic' forum.slug forum.pk topic.slug topic.pk %}?post={{ post.pk }}#{{ post.pk }}">&#182;</a>
              </h4>
              {% endspaceless %}
              <p>
                <small class="text-muted">
                {% spaceless %}
                <i class="fas fa-clock"></i>&nbsp;
                {% if post.poster %}
                {% url 'forum_member:profile' post.poster_id as poster_url %}
                {% blocktrans trimmed with poster_url=poster_url username=post.poster|forum_member_display_name creation_date=post.created %}
                  By: <a href="{{ poster_url }}">{{ username }}</a> on {{ creation_date }}
                {% endblocktrans %}
                {% else %}
                {% blocktrans trimmed with poster_username=post.username creation_date=post.created %}
                  By: {{ poster_username }} on {{ creation_date }}
                {% endblocktrans %}
                {% endif %}
                {% endspaceless %}
                </small>
              </p>
              <div class="post-content">
                {{ post.content.rendered }}
              </div>
              {% include "forum_conversation/forum_attachments/attachments_detail.html" %}
              {% if post.enable_signature and post.poster.forum_profile.signature %}
              <div class="post-signature">
                {{ post.poster.forum_profile.signature.rendered }}
              </div>
              {% endif %}
              {% if post.updates_count %}
              <div class="mt-4 edit-info">
                <small class="text-muted">
                  <i class="fas fa-edit"></i>&nbsp;{% if post.updated_by %}{% trans "Last edited by:" %}&nbsp;<a href="{% url 'forum_member:profile' post.updated_by_id %}">{{ post.updated_by|forum_member_display_name }}</a>&nbsp;{% else %}{% trans "Updated" %}&nbsp;{% endif %}{% trans "on" %}&nbsp;{{ post.updated }}, {% blocktrans count counter=post.updates_count %}edited {{counter }} time in total.{% plural %}edited {{counter }} times in total.{% endblocktrans %}
                </small>
                {% if post.update_reason %}
                <br />
                <small class="text-muted">
                  <b>{% trans "Reason:" %}</b>&nbsp;{{ post.update_reason }}
                </small>
                {% endif %}
              </div>
              {% endif %}
          </div>
          <div class="col-md-2 d-none d-md-block post-sidebar">
            {% if post.poster %}
            <div class="avatar">
              <a href="{% url 'forum_member:profile' post.poster_id %}">
                {% include "partials/avatar.html" with profile=post.poster.forum_profile show_placeholder=True %}
              </a>
            </div>
            <div class="username"><a href="{% url 'forum_member:profile' post.poster_id %}"><b>{{ post.poster|forum_member_display_name }}</b></a></div>
            <div class="posts-count text-muted"><b>{% trans "Posts:" %}</b>&nbsp;{{ post.poster.forum_profile.posts_count }}</div>
            {% else %}
            <div class="username"><b>{{ post.username }}</b></div>
            <div class="username text-muted">{% trans "Anonymous user" %}</div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
<div class="row">
  <div class="col-6 col-md-4 topic-actions-block">
    {% include "forum_conversation/partials/topic_detail_actions.html" %}
  </div>
  <div class="col-12 col-md-8">
    {% with "pagination-sm justify-content-end" as pagination_size %}
    {% include "partials/pagination.html" %}
    {% endwith %}
  </div>
</div>
{% endblock content %}

machina/templates/machina/forum_conversation/topic_list.html
{% load i18n %}
{% load forum_conversation_tags %}
{% load forum_member_tags %}
{% load forum_tracking_tags %}

{% if topics or not hide_if_empty %}
<div class="mb-3 row">
  <div class="col-12">
    <div class="card topiclist">
      <div class="p-0 card-header">
        <div class="row m-0 px-3 py-2">
          <div class="pl-0 col-md-8 col-sm-9 col-12 topic-name-col"><h3 class="m-0 card-title h5 text-dark"><i class="fas fa-comment"></i> {% trans topic_list_title %}</h3></div>
          <div class="col-md-1 d-none d-md-block text-center text-nowrap topic-count-col">{% trans "Replies" %}</div>
          <div class="col-md-1 d-none d-md-block text-center text-nowrap topic-count-col">{% trans "Views" %}</div>
          <div class="pr-0 col-md-2 col-sm-3 d-none d-sm-block text-nowrap topic-last-post-col">{% trans "Last post" %}</div>
        </div>
      </div>
      <div class="p-0 card-body">{% if not force_all_unread and unread_topics == None %}{% get_unread_topics topics request.user as unread_topics %}{% endif %}
      {% for topic in topics %}
      <div class="row m-0 px-3 py-2 border-bottom">
        <div class="pl-0 col-md-8 col-sm-9 col-xs-11 topic-name">
          <div class="topic-inline-pagination float-right d-none d-sm-block">{% topic_pages_inline_list topic %}</div>
          <table class="topic-data-table">
            <tr>
              <td class="pt-1 pr-3 align-top topic-icon {% if topic in unread_topics or force_all_unread %}unread{% endif %}">
                <i class="fas {% if topic.is_sticky %}fa-lightbulb{% elif topic.is_announce %}fa-info{% else %}fa-dot-circle{% endif %} fa-2x"></i>
              </td>
              <td class="align-top topic-name">
                <a href="{% url 'forum_conversation:topic' topic.forum.slug topic.forum.pk topic.slug topic.pk %}" class="topic-name-link">{{ topic.subject }}</a>{% if topic.is_locked %}&nbsp;<i class="fas fa-times-circle locked-indicator" title="{% trans 'This topic is locked' %}"></i>{% endif %}
                <div>
                  <div class="topic-created">
                  {% if topic.poster %}
                    {% url 'forum_member:profile' topic.poster_id as poster_url %}
                    {% blocktrans trimmed with poster_url=poster_url username=topic.poster|forum_member_display_name creation_date=topic.created %}
                      By: <a href="{{ poster_url }}">{{ username }}</a> on {{ creation_date }}
                    {% endblocktrans %}
                  {% else %}
                    {% blocktrans trimmed with poster_username=topic.first_post.username creation_date=topic.created %}
                      By: {{ poster_username }} on {{ creation_date }}
                    {% endblocktrans %}
                  {% endif %}
                  </div>
                </div>
              </td>
            </tr>
          </table>
        </div>
        <div class="py-2 col-md-1 d-none d-md-block text-center topic-count">{{ topic.posts_count|add:"-1" }}</div>
        <div class="py-2 col-md-1 d-none d-md-block text-center topic-count">{{ topic.views_count }}</div>
        <div class="py-2 col-md-2 col-sm-3 d-none d-sm-block topic-last-post">
        {% with last_post=topic.last_post %}
          {% if last_post.poster %}
            {% url 'forum_member:profile' last_post.poster_id as poster_url %}
            {% blocktrans trimmed with poster_url=poster_url username=last_post.poster|forum_member_display_name %}
              By: <a href="{{ poster_url }}">{{ username }}</a>
            {% endblocktrans %}
          {% else %}
            {% blocktrans trimmed with poster_username=last_post.username %}
              By: {{ poster_username }}
            {% endblocktrans %}
          {% endif %}
          &nbsp;<a href="{% url 'forum_conversation:topic' topic.forum.slug topic.forum.pk topic.slug topic.pk %}?post={{ last_post.pk }}#{{ last_post.pk }}"><i class="fas fa-arrow-circle-right "></i></a>
          <br />
          <small>{{ last_post.created }}</small>
        {% endwith %}
        </div>
      </div>
      {% empty %}
      <div class="row m-0 px-3 py-2">
        <div class="p-0 col-12">
        {% if empty_message %}
          {{ empty_message }}
        {% else %}
          {% trans "There are no topics in this forum." %}
        {% endif %}
        </div>
      </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endif %}

machina/templates/machina/forum_conversation/topic_pages_inline_list.html
{% load i18n %}

{% if first_pages %}
&#91;&nbsp;
{% trans "Go to the page:" %}&nbsp;
{% for page in first_pages %}
<a href="{% url 'forum_conversation:topic' topic.forum.slug topic.forum.id topic.slug topic.pk %}?page={{ page }}">{{ page }}</a>{% if not forloop.last %}&#44;&nbsp;{% elif forloop.last and last_page %}&#44;&nbsp;{% endif %}
{% endfor %}
{% if last_page %}
&#133;&#44;&nbsp;<a href="{% url 'forum_conversation:topic' topic.forum.slug topic.forum.id topic.slug topic.pk %}?page={{ last_page }}">{{ last_page }}</a>
{% endif %}
&nbsp;&#93;
{% endif %}